Feature: Q14

  Scenario Outline:Database üzerinden staff tablosundaki qualification=MS,specialization= Neurology olan iceriklerin
  account_title verilerini harf sirasina göre siralayarak listeyiniz.
    #Select account_title from staff where qualification='MS' and specialization= 'Neurology' order by account_title;
    Given Create connection
    Then Create a query that alphabetically sorts the "<account_titles>" of those whose qualification is "MS" and specialization is "Neurology"
    And the query result should be match based on staff table query
    Then close the connection
    Examples:
      | account_titles        |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | abdullah.ak           |
      | ahmet.bicakci         |
      | ahmet.bicakci         |
      | ahmet.bicakci         |
      | ahmet.bicakci         |
      | ahmet.dogan           |
      | ahmet.dogan           |
      | ahmet.dogan           |
      | ahmet.dogan           |
      | ahmet.emre.elieyioğlu |
      | ahmet.emre.elieyioğlu |
      | ahmet.emre.elieyioğlu |
      | ahmet.emre.elieyioğlu |
      | ahmet.yazicioglu      |
      | ahmet.yazicioglu      |
      | ahmet.yazicioglu      |
      | ahmet.yazicioglu      |
      | ali.mat               |
      | ali.mat               |
      | ali.mat               |
      | ali.mat               |
      | ali.tozcu             |
      | ali.tozcu             |
      | ali.tozcu             |
      | ali.tozcu             |
      | ayse.busra.pehlivan   |
      | ayse.busra.pehlivan   |
      | ayse.busra.pehlivan   |
      | ayse.busra.pehlivan   |
      | ayse.nuriye.alcik     |
      | ayse.nuriye.alcik     |
      | ayse.nuriye.alcik     |
      | ayse.nuriye.alcik     |
      | ayten.kok             |
      | ayten.kok             |
      | ayten.kok             |
      | ayten.kok             |
      | azat.ozay             |
      | azat.ozay             |
      | azat.ozay             |
      | azat.ozay             |
      | bektas.alakus         |
      | bektas.alakus         |
      | bektas.alakus         |
      | bektas.alakus         |
      | belkis.oruc           |
      | belkis.oruc           |
      | belkis.oruc           |
      | belkis.oruc           |
      | berivan.gencdal       |
      | berivan.gencdal       |
      | berivan.gencdal       |
      | berivan.gencdal       |
      | berkan.sonmezay       |
      | berkan.sonmezay       |
      | berkan.sonmezay       |
      | berkan.sonmezay       |
      | berrin.demir          |
      | berrin.demir          |
      | berrin.demir          |
      | berrin.demir          |
      | betul.ahlatci         |
      | betul.ahlatci         |
      | betul.ahlatci         |
      | betul.ahlatci         |
      | burhan.tastan         |
      | burhan.tastan         |
      | burhan.tastan         |
      | burhan.tastan         |
      | duygu.gunaydin        |
      | duygu.gunaydin        |
      | duygu.gunaydin        |
      | duygu.gunaydin        |
      | elif.isci             |
      | elif.isci             |
      | elif.isci             |
      | elif.isci             |
      | emine.bas             |
      | emine.bas             |
      | emine.bas             |
      | emine.bas             |
      | emre.karakullukcu     |
      | emre.karakullukcu     |
      | emre.karakullukcu     |
      | emre.karakullukcu     |
      | enver.kuris           |
      | enver.kuris           |
      | enver.kuris           |
      | enver.kuris           |
      | erhan.ciftci          |
      | erhan.ciftci          |
      | erhan.ciftci          |
      | erhan.ciftci          |
      | erman.coskun          |